### PR TITLE
Updated to 1.19.3

### PR DESCRIPTION
**Pull request by mdo992**
You can create a separate branch and merge this there because TF doesn't support 1.19.1 yet and I'm not too sure if it will. They might update and just disable chat signing.
Edit: Updated to 1.19.3

### CODE REVIEW

**Comment by hhhzzzsss** [comment]
I'll probably hold off on merging this until 1.19.1/1.19.2 support is added to TF, since that's the primary server this is used on.

**Comment by Joshua11TheHacker** [comment]
sus

**Comment by mdo992** [comment]
Closes #9

**Comment by mdo992** [comment]
> I'll probably hold off on merging this until 1.19.1/1.19.2 support is added to TF, since that's the primary server this is used on.

Support for 1.19 was added fairly recently.

**Comment by mdo992** [comment]
Tested and most functionality works (did not test the nbs converter and the song downloader though)

**Comment by hhhzzzsss** [comment]
Looks good, thanks! Sorry for the delay.

**Pull request merged**
